spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todeveloperdo?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&&allowPublicKeyRetrieval=true
    username: root
    password: wnstjr6522
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect

github:
  client-id: Iv23ctERiyiKyMTbHhx9
  client-secret: 1142a239e83e8222a57ffab1e49c3b506d2079d4
  redirect-uri: http://localhost:8080/login/oauth2/code/github



jwt:
  header: Authorization
  secret: 9340d95bs018cb37fedfce6f47c1b0b4426f87ada2a465c4f378dc8aca952d68677a58e5176c15d2c2c5167158224dbc509143c4042cda14b5c8120653068bc7XdyYETl1PVR1fHK3DRQwFTEXo+cXA28g1uEb2sTUN/Q=
  token-validity-in-seconds: 86400

feign:
  client:
    access-token:
      url: https://github.com
    user-profile:
      url: https://api.github.com